{% set name = "fermitools-build-deps" %}
{% set version = "1.2.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - ape 2.9
    - aplpy
    - astropy
    - blas 1.1
    - clhep 2.4.1.0
    - cppunit 1.14.0
    - f2c 0.0.1
    - fermi-repoman
    - fftw 3.3.8
    - git
    - gsl 2.2
    - healpix_cxx 3.31
    - matplotlib
    - numpy
    - openblas 0.2.19|0.2.19.*
    - pmw 2.0.1
    - python 2.7
    - readline 6.2
    - root5 5.34.38
    - scons 2.*
    - swig 3.0.12
    - wcslib 5.18
    - xerces-c 3.2.0

  run:
    - ape 2.9
    - aplpy
    - astropy
    - blas 1.1
    - clhep 2.4.1.0
    - cppunit 1.14.0
    - f2c 0.0.1
    - fermi-repoman
    - fftw 3.3.8
    - git
    - gsl 2.2
    - healpix_cxx 3.31
    - matplotlib
    - numpy
    - openblas 0.2.19|0.2.19.*
    - pmw 2.0.1
    - python 2.7
    - readline 6.2
    - root5 5.34.38
    - scons 2.*
    - swig 3.0.12
    - wcslib 5.18
    - xerces-c 3.2.0
