{% set name = "fermitools-build-deps" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('VERSION', 0)}}

# source:
#   git_url: https://github.com/fermi-lat/Fermitools-build-deps.git

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}

requirements:
  run:
    - packagedoesntexist
    - ape >=3
    - aplpy
    - astropy <4
    - blas
    - clhep 2.4.4.*
    - cppunit
    - f2c 0.0.2
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - minuit2
    - numpy >=1.17
    - openblas
    - pmw
    - python >=3.7
    - readline
    - scons 3.0.3.*
    - swig
    - wcslib 5.*
    - xerces-c
    - zstd 
