{% set name = "fermitools-build-deps" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('VERSION', 0)}}

# source:
#   git_url: https://github.com/fermi-lat/Fermitools-build-deps.git

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}
  
requirements:
  build:
    - fermi-repoman
    - clhep 2.4.4
  run:
    - ape >=3
    - aplpy
    - astropy
    - blas
    - clhep 2.4.4
    - cppunit
    - f2c 
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - libcxx
    - matplotlib
    - numpy >=1.17
    - openblas
    - pmw
    - python >=3.7
    - readline
    - root 
    - scons 3.0.3.*
    - swig
    - wcslib 5.*
    - xerces-c
    - zstd 
