{% set name = "fermitools-build-deps" %}
{% set version = "1.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - ape >=3
    - aplpy
    - astropy
    - blas
    - clhep
    - cppunit
    - f2c 0.0.2
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy >=1.17
    - openblas
    - pmw
    - python 3.7.*
    - readline
    - root >=6.0
    - scons 3.0.3
    - swig
    - wcslib 5.*
    - xerces-c
    - zstd 1.3.7

  run:
    - ape >=3
    - aplpy
    - astropy
    - blas
    - clhep
    - cppunit
    - f2c 0.0.2.*
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy >=1.11
    - pmw
    - python 2.7
    - root >=6.0
    - scipy
    - scons
    - swig
    - wcslib <6
    - xerces-c
