{% set name = "fermitools-build-deps" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
     
  build:
    - ape >=3
    - aplpy
    - astropy
    - blas
    - clhep
    - cppunit
    - f2c 0.0.2
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy >=1.11
    - pmw
    - python 2.7
    - root >=6.0
    - scipy
    - scons
    - swig
    - wcslib <6
    - xerces-c
    
  run:
    - ape >=3
    - aplpy
    - astropy
    - blas
    - clhep
    - cppunit
    - f2c 0.0.2
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy >=1.11
    - pmw
    - python 2.7
    - root >=6.0
    - scipy
    - scons
    - swig
    - wcslib <6
    - xerces-c
